# NumPy 

# Question 1:
Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays


In [1]:
import numpy as np


In [2]:
a = np.random.choice(10, 10, replace=False)
b = np.round([0.121, 1.26253, 1.0041, 3, 2, 5, 2.1341, 7.234, 8.8762, 9], decimals=1)

print(a)
print(b)
print()
print("Comparison --> greater",'\n')
print(np.greater(a, b),'\n')
print("Comparison --> greater_equal",'\n')
print(np.greater_equal(a, b),'\n')
print("Comparison --> less",'\n')
print(np.less(a, b),'\n')
print("Comparison --> less_equal",'\n')
print(np.less_equal(a, b),'\n')



[4 7 1 6 8 2 0 3 9 5]
[0.1 1.3 1.  3.  2.  5.  2.1 7.2 8.9 9. ]

Comparison --> greater 

[ True  True False  True  True False False False  True False] 

Comparison --> greater_equal 

[ True  True  True  True  True False False False  True False] 

Comparison --> less 

[False False False False False  True  True  True False  True] 

Comparison --> less_equal 

[False False  True False False  True  True  True False  True] 



# Question 2:
Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives


In [3]:
x = np.zeros(10, np.int64)
print(x,'\n')

y = np.ones(10, np.int64)
print(y,'\n')

z = np.ones(10, np.int32)*5
print(z)

[0 0 0 0 0 0 0 0 0 0] 

[1 1 1 1 1 1 1 1 1 1] 

[5 5 5 5 5 5 5 5 5 5]


# Question 3:
Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a
given array


In [4]:
array = np.random.choice(18, 42, replace=True).reshape(6,7)
print(array,'\n')

print("Columnwise addition => ",np.sum(array, axis=0),'\n')
print('Rowwise addition => ',np.sum(array, axis=1))

[[ 7 14 13  9 10  8  4]
 [ 3 14  6 12 13  6  8]
 [ 3 17 15  8 12 16 13]
 [ 0 11  5  9  6  7 14]
 [17 15  6 17 16  0  2]
 [10  4 13  6 11  9  3]] 

Columnwise addition =>  [40 75 58 61 68 46 44] 

Rowwise addition =>  [65 62 84 52 73 56]


# Question 4:
Write a NumPy program to add, subtract, multiply, divide arguments element-wise.



In [5]:
arr1 = np.random.choice(10, 20, replace=True).reshape(4,5)
arr2 = (np.ones(20, np.int32)*2).reshape(4,5)

print('arr1 => \n',arr1,'\n')
print('arr2 => \n' ,arr2)

print("\nElementwise Addition \n", arr1 + arr2)

print("\nElementwise Multiply \n", arr1 * arr2)

print("\nElementwise Division \n", arr1 / arr2)

arr1 => 
 [[5 1 4 6 0]
 [8 1 5 2 2]
 [4 1 9 0 7]
 [6 5 7 4 4]] 

arr2 => 
 [[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]

Elementwise Addition 
 [[ 7  3  6  8  2]
 [10  3  7  4  4]
 [ 6  3 11  2  9]
 [ 8  7  9  6  6]]

Elementwise Multiply 
 [[10  2  8 12  0]
 [16  2 10  4  4]
 [ 8  2 18  0 14]
 [12 10 14  8  8]]

Elementwise Division 
 [[2.5 0.5 2.  3.  0. ]
 [4.  0.5 2.5 1.  1. ]
 [2.  0.5 4.5 0.  3.5]
 [3.  2.5 3.5 2.  2. ]]


# Question 5:
Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in
degree.

In [6]:
print("sine: array of angles given in degrees \n")
print(np.sin(np.array((0, 30, 45, 60, 90)) * 3.14 / 180))

print("\n cosine: array of angles given in degrees\n")
print(np.cos(np.array((0, 30, 45, 60, 90)) *  (22/7) * 180))

print("\ntangent: array of random angles\n" )
print(np.tan(np.array((0., 30., 40., 45., 60., 75., 90., 180., 360.))* np.pi/180.))

sine: array of angles given in degrees 

[0.         0.4997701  0.70682518 0.86575984 0.99999968]

 cosine: array of angles given in degrees

[ 1.          0.85509788 -0.68398486  0.46238476 -0.06432943]

tangent: array of random angles

[ 0.00000000e+00  5.77350269e-01  8.39099631e-01  1.00000000e+00
  1.73205081e+00  3.73205081e+00  1.63312394e+16 -1.22464680e-16
 -2.44929360e-16]
