# NumPy 

# Question 1:
Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays


In [1]:
import numpy as np


In [2]:
a = np.random.choice(10, 10, replace=False)
b = np.round([0.121, 1.26253, 1.0041, 3, 2, 5, 2.1341, 7.234, 8.8762, 9], decimals=1)

print(a)
print(b)
print()
print("Comparison --> greater",'\n')
print(np.greater(a, b),'\n')
print("Comparison --> greater_equal",'\n')
print(np.greater_equal(a, b),'\n')
print("Comparison --> less",'\n')
print(np.less(a, b),'\n')
print("Comparison --> less_equal",'\n')
print(np.less_equal(a, b),'\n')



[7 1 0 5 8 6 9 4 3 2]
[0.1 1.3 1.  3.  2.  5.  2.1 7.2 8.9 9. ]

Comparison --> greater 

[ True False False  True  True  True  True False False False] 

Comparison --> greater_equal 

[ True False False  True  True  True  True False False False] 

Comparison --> less 

[False  True  True False False False False  True  True  True] 

Comparison --> less_equal 

[False  True  True False False False False  True  True  True] 



# Question 2:
Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives


In [3]:
x = np.zeros(10, np.int64)
print(x,'\n')

y = np.ones(10, np.int64)
print(y,'\n')

z = np.ones(10, np.int32)*5
print(z)

[0 0 0 0 0 0 0 0 0 0] 

[1 1 1 1 1 1 1 1 1 1] 

[5 5 5 5 5 5 5 5 5 5]


# Question 3:
Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a
given array


In [4]:
array = np.random.choice(18, 42, replace=True).reshape(6,7)
print(array,'\n')

print("Columnwise addition => ",np.sum(array, axis=0),'\n')
print('Rowwise addition => ',np.sum(array, axis=1))

[[ 1  4  0 12 14  4 16]
 [ 7 17  2 11  3  9  2]
 [ 0 10  6  7 10  5 15]
 [ 4 11  2  2 16 13 10]
 [ 4 16  0  8  0  8  2]
 [11  4  4 16 10  1  8]] 

Columnwise addition =>  [27 62 14 56 53 40 53] 

Rowwise addition =>  [51 51 53 58 38 54]


# Question 4:
Write a NumPy program to add, subtract, multiply, divide arguments element-wise.



In [5]:
arr1 = np.random.choice(10, 20, replace=True).reshape(4,5)
arr2 = (np.ones(20, np.int32)*2).reshape(4,5)

print('arr1 => \n',arr1,'\n')
print('arr2 => \n' ,arr2)

print("\nElementwise Addition \n", arr1 + arr2)

print("\nElementwise Multiply \n", arr1 * arr2)

print("\nElementwise Division \n", arr1 / arr2)

arr1 => 
 [[5 5 2 6 0]
 [3 0 5 0 0]
 [5 3 1 3 2]
 [8 1 3 4 8]] 

arr2 => 
 [[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]

Elementwise Addition 
 [[ 7  7  4  8  2]
 [ 5  2  7  2  2]
 [ 7  5  3  5  4]
 [10  3  5  6 10]]

Elementwise Multiply 
 [[10 10  4 12  0]
 [ 6  0 10  0  0]
 [10  6  2  6  4]
 [16  2  6  8 16]]

Elementwise Division 
 [[2.5 2.5 1.  3.  0. ]
 [1.5 0.  2.5 0.  0. ]
 [2.5 1.5 0.5 1.5 1. ]
 [4.  0.5 1.5 2.  4. ]]


# Question 5:
Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in
degree.

In [6]:
print("sine: array of angles given in degrees \n")
print(np.sin(np.array((0, 30, 45, 60, 90)) * 3.14 / 180))

print("\n cosine: array of angles given in degrees\n")
print(np.cos(np.array((0, 30, 45, 60, 90)) *  (22/7) * 180))

print("\ntangent: array of random angles\n" )
print(np.tan(np.array((0., 30., 40., 45., 60., 75., 90., 180., 360.))* np.pi/180.))

sine: array of angles given in degrees 

[0.         0.4997701  0.70682518 0.86575984 0.99999968]

 cosine: array of angles given in degrees

[ 1.          0.85509788 -0.68398486  0.46238476 -0.06432943]

tangent: array of random angles

[ 0.00000000e+00  5.77350269e-01  8.39099631e-01  1.00000000e+00
  1.73205081e+00  3.73205081e+00  1.63312394e+16 -1.22464680e-16
 -2.44929360e-16]


# Pandas 

# Question 6
write a Pandas Program to create and display a DataFrame from a specified dictionary data which has the index labels

In [7]:
import pandas as pd
import numpy as np

dic = { 'Name' : pd.Series(['Dhruv','Raj','Mithil'],index=[1,2,3]),
        
       'Age' : pd.Series([21,22,21],index=[1,2,3],dtype='int8') ,
       
       'Height' : pd.Series([5.54, 5.60, 5.53],index=[1,2,3]),
       
       'sex' : pd.Series(['m','m','m'],index=[1,2,3]) 
      }
dic

{'Name': 1     Dhruv
 2       Raj
 3    Mithil
 dtype: object,
 'Age': 1    21
 2    22
 3    21
 dtype: int8,
 'Height': 1    5.54
 2    5.60
 3    5.53
 dtype: float64,
 'sex': 1    m
 2    m
 3    m
 dtype: object}

In [8]:
df = pd.DataFrame(dic)
df

Name  Age  Height sex
1   Dhruv   21    5.54   m
2     Raj   22    5.60   m
3  Mithil   21    5.53   m

# Question 7
Write a Pandas program to select the 'name' and 'score' columns from the following DataFrame

In [9]:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

frame = pd.DataFrame(exam_data, labels)
frame

name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

In [10]:
frame[['name','score']]

name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0

# Question 8 
Write a Pandas program to join the two given dataframes along rows and assign all data

In [11]:
stu_data1 = pd.DataFrame({
        'student_id': ['S1', 'S2', 'S3', 'S4', 'S5'],
         'name': ['Danniella Fenton', 'Ryder Storey', 'Bryce Jensen', 'Ed Bernal', 'Kwame Morin'], 
        'marks': [200, 210, 190, 222, 199]})

stu_data2 = pd.DataFrame({
        'student_id': ['S4', 'S5', 'S6', 'S7', 'S8'],
        'name': ['Scarlette Fisher', 'Carla Williamson', 'Dante Morse', 'Kaiser William', 'Madeeha Preston'], 
        'marks': [201, 200, 198, 219, 201]})


In [12]:
pd.concat([stu_data1, stu_data2])

student_id              name  marks
0         S1  Danniella Fenton    200
1         S2      Ryder Storey    210
2         S3      Bryce Jensen    190
3         S4         Ed Bernal    222
4         S5       Kwame Morin    199
0         S4  Scarlette Fisher    201
1         S5  Carla Williamson    200
2         S6       Dante Morse    198
3         S7    Kaiser William    219
4         S8   Madeeha Preston    201

# Question 9
Write a Pandas program to detect missing values of a given DataFrame. Display True or False.

In [13]:
frame.isna()

name  score  attempts  qualify
a  False  False     False    False
b  False  False     False    False
c  False  False     False    False
d  False   True     False    False
e  False  False     False    False
f  False  False     False    False
g  False  False     False    False
h  False   True     False    False
i  False  False     False    False
j  False  False     False    False

# Question 10
Write a Pandas program to create and display a one-dimentional array-like object containing an array of data.

In [14]:
np.ones(10)


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
d1 = pd.DataFrame(np.ones(10),columns=['numpy_ones'] ,index=['a','b','c','d','e','f','g','h','i','j'])
d1

numpy_ones
a         1.0
b         1.0
c         1.0
d         1.0
e         1.0
f         1.0
g         1.0
h         1.0
i         1.0
j         1.0